import{i as p,S as g,a as y}from"./assets/vendor-89feecc5.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();function c(t){p.show({close:!1,closeOnClick:!0,message:t,messageColor:"white",timeout:3e3,transitionIn:"flipInX",transitionOut:"flipOutX",position:"topRight",backgroundColor:"#EF4040",progressBar:!1})}let L=new g("#gallery a",{showCounter:!1,captionsData:"alt",captionDelay:200});const v=document.querySelector("#form"),f=document.querySelector("#gallery"),u=document.querySelector(".loader"),i=document.querySelector(".loader-button"),m=40;let n=1,d;v.addEventListener("submit",b);i.addEventListener("click",w);async function b(t){t.preventDefault(),u.classList.remove("hidden"),f.innerHTML="",n=1,d=t.currentTarget.elements.inputToSearch.value.trim(),t.currentTarget.reset(),i.classList.add("hidden"),await h(d)}async function w(){i.classList.add("hidden"),u.classList.remove("hidden"),n+=1,await h(d)}async function h(t){try{const o=new URLSearchParams({key:"41535570-7b1028e1c6f1b041bb0744cc1",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:m}),a=(await y.get(`https://pixabay.com/api/?${o}`)).data;a.hits.length===0?(c("Sorry, there are no images matching your search query. Please try again!"),i.classList.add("hidden")):(S(a),q(a.totalHits),L.refresh())}catch(o){c(`Api request error: ${o}`)}finally{u.classList.add("hidden")}}function S(t){const o=t.hits.map(r=>`<li class="gallery-item">
        <a href="${r.largeImageURL}">
          <img class="gallery-img" src="${r.webformatURL}" alt="${r.tags}" loading="lazy"/>
        </a>
        <div class="image-info">
          <div>Likes:<span>${r.likes}</span></div>
          <div>Views:<span>${r.views}</span></div>
          <div>Comments:<span>${r.comments}</span></div>
          <div>Downloads:<span>${r.downloads}</span></div>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",o)}function q(t){const o=Math.ceil(t/m);n>=o?c("We are sorry, but you have reached the end of search results."):(i.classList.remove("hidden"),n>=2&&I())}function I(){const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
